"""initial_schema

Revision ID: 00e875a56f36
Revises: 
Create Date: 2026-08-25 12:45:16.831532

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e875a56f36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_branch_id'), 'admins', ['branch_id'], unique=False)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('monthly_target', sa.Float(), nullable=False),
    sa.Column('daily_target', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_branch_id'), 'employees', ['branch_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_branch_id'), 'audit_logs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('assigned_employee_id', sa.Integer(), nullable=True),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('customer_type', sa.String(length=50), nullable=False),
    sa.Column('lead_source', sa.String(length=50), nullable=False),
    sa.Column('interested_category', sa.String(length=100), nullable=False),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('first_contact_date', sa.Date(), nullable=False),
    sa.Column('last_contact_date', sa.Date(), nullable=False),
    sa.Column('next_followup_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_assigned_employee_id'), 'customers', ['assigned_employee_id'], unique=False)
    op.create_index(op.f('ix_customers_branch_id'), 'customers', ['branch_id'], unique=False)
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_next_followup_date'), 'customers', ['next_followup_date'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('daily_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('customers_approached', sa.Integer(), nullable=False),
    sa.Column('customers_visited', sa.Integer(), nullable=False),
    sa.Column('new_enquiries', sa.Integer(), nullable=False),
    sa.Column('followups', sa.Integer(), nullable=False),
    sa.Column('product_demos', sa.Integer(), nullable=False),
    sa.Column('quotations_given', sa.Integer(), nullable=False),
    sa.Column('customers_converted', sa.Integer(), nullable=False),
    sa.Column('sales_count', sa.Integer(), nullable=False),
    sa.Column('gold_sales_value', sa.Float(), nullable=False),
    sa.Column('diamond_sales_value', sa.Float(), nullable=False),
    sa.Column('silver_sales_value', sa.Float(), nullable=False),
    sa.Column('other_sales_value', sa.Float(), nullable=False),
    sa.Column('total_sales_value', sa.Float(), nullable=False),
    sa.Column('completed_followups', sa.Integer(), nullable=False),
    sa.Column('pending_followups', sa.Integer(), nullable=False),
    sa.Column('lost_customers', sa.Integer(), nullable=False),
    sa.Column('lost_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_employee_daily_performance')
    )
    op.create_index(op.f('ix_daily_performances_branch_id'), 'daily_performances', ['branch_id'], unique=False)
    op.create_index(op.f('ix_daily_performances_date'), 'daily_performances', ['date'], unique=False)
    op.create_index(op.f('ix_daily_performances_employee_id'), 'daily_performances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_daily_performances_id'), 'daily_performances', ['id'], unique=False)
    op.create_table('employee_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month_year', sa.String(length=7), nullable=False),
    sa.Column('sales_target', sa.Float(), nullable=False),
    sa.Column('approach_target', sa.Integer(), nullable=False),
    sa.Column('conversion_target', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_targets_employee_id'), 'employee_targets', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_targets_id'), 'employee_targets', ['id'], unique=False)
    op.create_index(op.f('ix_employee_targets_month_year'), 'employee_targets', ['month_year'], unique=False)
    op.create_table('customer_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_interactions_branch_id'), 'customer_interactions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_customer_id'), 'customer_interactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_employee_id'), 'customer_interactions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_id'), 'customer_interactions', ['id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_branch_id'), 'follow_ups', ['branch_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_customer_id'), 'follow_ups', ['customer_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_employee_id'), 'follow_ups', ['employee_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_id'), 'follow_ups', ['id'], unique=False)
    op.create_index(op.f('ix_follow_ups_scheduled_date'), 'follow_ups', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_follow_ups_status'), 'follow_ups', ['status'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('total_gross_weight', sa.Float(), nullable=False),
    sa.Column('total_net_weight', sa.Float(), nullable=False),
    sa.Column('total_making_charges', sa.Float(), nullable=False),
    sa.Column('total_discount', sa.Float(), nullable=False),
    sa.Column('total_gst', sa.Float(), nullable=False),
    sa.Column('final_sale_value', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_branch_id'), 'sales', ['branch_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_employee_id'), 'sales', ['employee_id'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_index(op.f('ix_sales_invoice_number'), 'sales', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_sales_purchase_date'), 'sales', ['purchase_date'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('metal_purity', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('gross_weight', sa.Float(), nullable=False),
    sa.Column('net_weight', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_rate', sa.Float(), nullable=False),
    sa.Column('making_charges', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_id'), 'sale_items', ['id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_sales_purchase_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_invoice_number'), table_name='sales')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_employee_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_branch_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_follow_ups_status'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_scheduled_date'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_employee_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_customer_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_branch_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_customer_interactions_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_employee_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_customer_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_branch_id'), table_name='customer_interactions')
    op.drop_table('customer_interactions')
    op.drop_index(op.f('ix_employee_targets_month_year'), table_name='employee_targets')
    op.drop_index(op.f('ix_employee_targets_id'), table_name='employee_targets')
    op.drop_index(op.f('ix_employee_targets_employee_id'), table_name='employee_targets')
    op.drop_table('employee_targets')
    op.drop_index(op.f('ix_daily_performances_id'), table_name='daily_performances')
    op.drop_index(op.f('ix_daily_performances_employee_id'), table_name='daily_performances')
    op.drop_index(op.f('ix_daily_performances_date'), table_name='daily_performances')
    op.drop_index(op.f('ix_daily_performances_branch_id'), table_name='daily_performances')
    op.drop_table('daily_performances')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_next_followup_date'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_index(op.f('ix_customers_branch_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_assigned_employee_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_branch_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_branch_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_branch_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
