from backend.app.schemas.auth import LoginRequest, TokenResponse, ManagerProfile, MessageResponse
from backend.app.schemas.branch import BranchBase, BranchCard, BranchResponse
from backend.app.schemas.employee import (
    EmployeeBase,
    EmployeeCreate,
    EmployeeUpdate,
    EmployeeResponse,
    EmployeeDetailResponse,
)
from backend.app.schemas.activity import (
    CustomerActivityCreate,
    CustomerActivityResponse,
    SchemeRecordCreate,
    SchemeRecordResponse,
    FormMediaResponse,
    GoogleReviewCreate,
    GoogleReviewResponse,
    AttireRecordCreate,
    AttireRecordResponse,
)
from backend.app.schemas.outdoor_marketing import (
    OutdoorMarketingOverview,
    OutdoorAreaCreate,
    OutdoorAreaResponse,
    OutdoorCustomerCreate,
    OutdoorCustomerResponse,
    OutdoorSchemeCreate,
    OutdoorSchemeResponse,
    OutdoorActivityCreate,
    OutdoorActivityResponse,
)
from backend.app.schemas.dashboard import DashboardOverviewResponse

__all__ = [
    "LoginRequest",
    "TokenResponse",
    "ManagerProfile",
    "MessageResponse",
    "BranchBase",
    "BranchCard",
    "BranchResponse",
    "EmployeeBase",
    "EmployeeCreate",
    "EmployeeUpdate",
    "EmployeeResponse",
    "EmployeeDetailResponse",
    "CustomerActivityCreate",
    "CustomerActivityResponse",
    "SchemeRecordCreate",
    "SchemeRecordResponse",
    "FormMediaResponse",
    "GoogleReviewCreate",
    "GoogleReviewResponse",
    "AttireRecordCreate",
    "AttireRecordResponse",
    "OutdoorMarketingOverview",
    "OutdoorAreaCreate",
    "OutdoorAreaResponse",
    "OutdoorCustomerCreate",
    "OutdoorCustomerResponse",
    "OutdoorSchemeCreate",
    "OutdoorSchemeResponse",
    "OutdoorActivityCreate",
    "OutdoorActivityResponse",
    "DashboardOverviewResponse",
]
